import type { Category, Product, Banner, Collection } from './types';

// Categories / Collections
export const categories: (Category & Collection)[] = [
  {
    id: '1',
    name: 'Grocery',
    title: 'Grocery',
    handle: 'grocery',
    icon: 'ShoppingBasket',
    subcategories: ['Staples', 'Snacks', 'Beverages', 'Packaged Foods']
  },
  {
    id: '2',
    name: 'Electronics',
    title: 'Electronics',
    handle: 'electronics',
    icon: 'Smartphone',
    subcategories: ['Mobiles', 'Laptops', 'TV', 'Accessories']
  },
  {
    id: '3',
    name: 'Fashion',
    title: 'Fashion',
    handle: 'fashion',
    icon: 'Shirt',
    subcategories: ['Men', 'Women', 'Kids', 'Footwear']
  },
  {
    id: '4',
    name: 'Home & Kitchen',
    title: 'Home & Kitchen',
    handle: 'home-kitchen',
    icon: 'Home',
    subcategories: ['Furniture', 'Decor', 'Kitchen', 'Dining']
  },
  {
    id: '5',
    name: 'Premium Fruits',
    title: 'Premium Fruits',
    handle: 'premium-fruits',
    icon: 'Apple',
    subcategories: ['Apples', 'Exotic', 'Seasonal', 'Organic']
  },
  {
    id: '6',
    name: 'Dairy & Bakery',
    title: 'Dairy & Bakery',
    handle: 'dairy-bakery',
    icon: 'Milk',
    subcategories: ['Milk', 'Cheese', 'Bread', 'Cakes']
  },
  {
    id: '7',
    name: 'Personal Care',
    title: 'Personal Care',
    handle: 'personal-care',
    icon: 'Sparkles',
    subcategories: ['Skin', 'Hair', 'Oral', 'Hygiene']
  },
  {
    id: '8',
    name: 'Beauty',
    title: 'Beauty',
    handle: 'beauty',
    icon: 'Palette',
    subcategories: ['Makeup', 'Fragrance', 'Tools', 'Skincare']
  }
];

export const banners: Banner[] = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&h=400&fit=crop',
    title: 'Fresh Grocery Deals',
    link: '/category/grocery'
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1607082348824-92a7ab8d0d74?w=1200&h=400&fit=crop',
    title: 'Electronics Sale',
    link: '/category/electronics'
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&h=400&fit=crop',
    title: 'Fashion Week',
    link: '/category/fashion'
  }
];

export const mockProductsList: Product[] = [
  {
    id: '1',
    name: 'Tata Sampann Unpolished Toor Dal',
    title: 'Tata Sampann Unpolished Toor Dal',
    description: 'Premium quality unpolished toor dal for healthy cooking',
    handle: 'tata-sampann-unpolished-toor-dal',
    price: 149,
    originalPrice: 185,
    discount: 19,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&h=300&fit=crop'],
    category: 'Grocery',
    productType: 'Grocery',
    vendor: 'Tata',
    tags: ['dal', 'groceries', 'staples'],
    rating: 4.3,
    reviews: 1250,
    inStock: true,
    availableForSale: true,
    quantity: '1 kg',
    variantId: 'gid://shopify/ProductVariant/1'
  },
  {
    id: '2',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    title: 'Fortune Sunlite Refined Sunflower Oil',
    description: 'Light and healthy refined sunflower oil',
    handle: 'fortune-sunlite-refined-sunflower-oil',
    price: 185,
    originalPrice: 220,
    discount: 16,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&h=300&fit=crop'],
    category: 'Grocery',
    productType: 'Grocery',
    vendor: 'Fortune',
    tags: ['oil', 'cooking', 'groceries'],
    rating: 4.5,
    reviews: 890,
    inStock: true,
    availableForSale: true,
    quantity: '1 L',
    variantId: 'gid://shopify/ProductVariant/2'
  },
  {
    id: '3',
    name: 'Samsung Galaxy M34 5G',
    title: 'Samsung Galaxy M34 5G',
    description: '5G smartphone with amazing camera and battery life',
    handle: 'samsung-galaxy-m34-5g',
    price: 18999,
    originalPrice: 24999,
    discount: 24,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300&h=300&fit=crop'],
    category: 'Electronics',
    productType: 'Electronics',
    vendor: 'Samsung',
    tags: ['mobile', '5g', 'smartphone'],
    rating: 4.4,
    reviews: 3200,
    inStock: true,
    availableForSale: true,
    quantity: '1 pc',
    variantId: 'gid://shopify/ProductVariant/3'
  },
  {
    id: '4',
    name: 'Redmi 12 5G Pastel Blue',
    title: 'Redmi 12 5G Pastel Blue',
    description: 'Affordable 5G smartphone with stunning design',
    handle: 'redmi-12-5g-pastel-blue',
    price: 11999,
    originalPrice: 15999,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=300&h=300&fit=crop'],
    category: 'Electronics',
    productType: 'Electronics',
    vendor: 'Redmi',
    tags: ['mobile', '5g', 'smartphone'],
    rating: 4.2,
    reviews: 1500,
    inStock: true,
    availableForSale: true,
    quantity: '1 pc',
    variantId: 'gid://shopify/ProductVariant/4'
  },
  {
    id: '5',
    name: 'Levis Men Slim Fit Jeans',
    title: 'Levis Men Slim Fit Jeans',
    description: 'Stylish slim fit jeans for men',
    handle: 'levis-men-slim-fit-jeans',
    price: 1799,
    originalPrice: 2999,
    discount: 40,
    image: 'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=300&h=300&fit=crop'],
    category: 'Fashion',
    productType: 'Fashion',
    vendor: 'Levis',
    tags: ['jeans', 'men', 'clothing'],
    rating: 4.1,
    reviews: 650,
    inStock: true,
    availableForSale: true,
    quantity: '1 pc',
    variantId: 'gid://shopify/ProductVariant/5'
  },
  {
    id: '6',
    name: 'Puma Running Shoes',
    title: 'Puma Running Shoes',
    description: 'Comfortable running shoes for daily workout',
    handle: 'puma-running-shoes',
    price: 2499,
    originalPrice: 4499,
    discount: 44,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=300&fit=crop'],
    category: 'Fashion',
    productType: 'Fashion',
    vendor: 'Puma',
    tags: ['shoes', 'running', 'sports'],
    rating: 4.3,
    reviews: 420,
    inStock: true,
    availableForSale: true,
    quantity: '1 pair',
    variantId: 'gid://shopify/ProductVariant/6'
  },
  {
    id: '7',
    name: 'Fresh Apples - Shimla',
    title: 'Fresh Apples - Shimla',
    description: 'Fresh and juicy Shimla apples',
    handle: 'fresh-apples-shimla',
    price: 129,
    originalPrice: 159,
    discount: 19,
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=300&h=300&fit=crop'],
    category: 'Premium Fruits',
    productType: 'Premium Fruits',
    vendor: 'Fresh Farm',
    tags: ['fruits', 'apple', 'fresh'],
    rating: 4.6,
    reviews: 2100,
    inStock: true,
    availableForSale: true,
    quantity: '500 g',
    variantId: 'gid://shopify/ProductVariant/7'
  },
  {
    id: '8',
    name: 'Amul Full Cream Milk',
    title: 'Amul Full Cream Milk',
    description: 'Pure and fresh full cream milk',
    handle: 'amul-full-cream-milk',
    price: 68,
    originalPrice: 72,
    discount: 6,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&h=300&fit=crop'],
    category: 'Dairy & Bakery',
    productType: 'Dairy & Bakery',
    vendor: 'Amul',
    tags: ['milk', 'dairy', 'fresh'],
    rating: 4.7,
    reviews: 5600,
    inStock: true,
    availableForSale: true,
    quantity: '1 L',
    variantId: 'gid://shopify/ProductVariant/8'
  },
  {
    id: '9',
    name: 'Dove Deep Moisture Body Wash',
    title: 'Dove Deep Moisture Body Wash',
    description: 'Nourishing body wash for soft skin',
    handle: 'dove-deep-moisture-body-wash',
    price: 199,
    originalPrice: 249,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&h=300&fit=crop'],
    category: 'Personal Care',
    productType: 'Personal Care',
    vendor: 'Dove',
    tags: ['bodywash', 'skincare', 'personalcare'],
    rating: 4.4,
    reviews: 890,
    inStock: true,
    availableForSale: true,
    quantity: '200 ml',
    variantId: 'gid://shopify/ProductVariant/9'
  },
  {
    id: '10',
    name: 'Lakme 9 to 5 Lipstick',
    title: 'Lakme 9 to 5 Lipstick',
    description: 'Long-lasting matte lipstick',
    handle: 'lakme-9-to-5-lipstick',
    price: 299,
    originalPrice: 450,
    discount: 34,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&h=300&fit=crop'],
    category: 'Beauty',
    productType: 'Beauty',
    vendor: 'Lakme',
    tags: ['lipstick', 'makeup', 'beauty'],
    rating: 4.2,
    reviews: 340,
    inStock: true,
    availableForSale: true,
    quantity: '1 pc',
    variantId: 'gid://shopify/ProductVariant/10'
  },
  {
    id: '11',
    name: 'Aashirvaad Atta Whole Wheat',
    title: 'Aashirvaad Atta Whole Wheat',
    description: 'Premium quality whole wheat flour',
    handle: 'aashirvaad-atta-whole-wheat',
    price: 245,
    originalPrice: 295,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300&h=300&fit=crop'],
    category: 'Grocery',
    productType: 'Grocery',
    vendor: 'Aashirvaad',
    tags: ['atta', 'wheat', 'groceries'],
    rating: 4.5,
    reviews: 2300,
    inStock: true,
    availableForSale: true,
    quantity: '5 kg',
    variantId: 'gid://shopify/ProductVariant/11'
  },
  {
    id: '12',
    name: 'Sony WH-1000XM4 Headphones',
    title: 'Sony WH-1000XM4 Headphones',
    description: 'Industry-leading noise canceling headphones',
    handle: 'sony-wh-1000xm4-headphones',
    price: 24990,
    originalPrice: 29990,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop'],
    category: 'Electronics',
    productType: 'Electronics',
    vendor: 'Sony',
    tags: ['headphones', 'audio', 'electronics'],
    rating: 4.6,
    reviews: 1200,
    inStock: true,
    availableForSale: true,
    quantity: '1 pc',
    variantId: 'gid://shopify/ProductVariant/12'
  }
];

// Export for backward compatibility
export { mockProductsList as products };

export const deals = [
  { id: '1', title: 'Grocery Deals', subtitle: 'Up to 50% OFF', color: 'bg-green-100', icon: 'ShoppingBasket' },
  { id: '2', title: 'Electronics Sale', subtitle: 'Up to 40% OFF', color: 'bg-blue-100', icon: 'Smartphone' },
  { id: '3', title: 'Fashion Week', subtitle: 'Min 50% OFF', color: 'bg-pink-100', icon: 'Shirt' },
  { id: '4', title: 'Home Essentials', subtitle: 'Up to 60% OFF', color: 'bg-orange-100', icon: 'Home' }
];
